export interface XacroPatchChild {
  key: string;
  tagName: string;
}

export function assertPatchableXacroModel({
  sourceContent,
  sourceChildKeys,
  generatedChildren,
  changedKeys,
  mode,
}: {
  sourceContent: string;
  sourceChildKeys: ReadonlySet<string>;
  generatedChildren: XacroPatchChild[];
  changedKeys: ReadonlySet<string>;
  mode: 'strict' | 'direct-changes';
}): void {
  if (mode === 'direct-changes') {
    return;
  }
  const hasComplexXacro = /<\s*xacro:(?:macro|include)\b|\$\{|\$\(/i.test(sourceContent);
  if (!hasComplexXacro) {
    return;
  }

  const missingChangedModelKeys = generatedChildren.filter(
    (child) =>
      (child.tagName === 'link' || child.tagName === 'joint') &&
      changedKeys.has(child.key) &&
      !sourceChildKeys.has(child.key),
  );

  if (missingChangedModelKeys.length > 0) {
    throw new SourcePreservingExportError(
      'Cannot preserve Xacro text structure because links or joints are generated by macros/includes.',
    );
  }
}
import { SourcePreservingExportError } from './xmlSourcePatch';
