import { ensureXacroNamespace } from '@/core/parsers';
import type { RobotData, RobotFile, RobotState } from '@/types';
import { resolveSourcePreservingExportContent } from '@/app/hooks/sourcePreservingExportUtils';
import {
  collectDirectChildren,
  getElementAttribute,
} from '@/app/hooks/source-preserving-export/xmlSourcePatch';
import { generateEditableRobotSource } from './generateEditableRobotSource';
import { parseEditableRobotSource } from './parseEditableRobotSource';
import {
  applyFineGrainedUrdfPatches,
  asRobotState,
  findByStableIdentity,
  hasSameValue,
  reconcileStandardUrdfReferences,
  sourceSemanticHash,
  sourceSemanticHashForWorkspace,
} from './urdfEditableSourceReconciler';

export interface ReconcileXacroEditableSourceOptions {
  sourceContent: string;
  beforeRobot: RobotData;
  afterRobot: RobotData;
  sourceFileName: string;
  availableFiles?: RobotFile[];
  allFileContents?: Record<string, string>;
}

export type ReconcileXacroEditableSourceResult =
  | { status: 'patched'; content: string }
  | { status: 'unsafe'; reason: string };

type EntityKind = 'link' | 'joint';

interface ChangedEntity {
  kind: EntityKind;
  beforeName?: string;
  afterName?: string;
}

const XACRO_DYNAMIC_NODE_RE = /<\s*\/?\s*xacro:|\$\{|\$\(/i;

function parseXacro({
  sourceFileName,
  sourceContent,
  availableFiles = [],
  allFileContents = {},
}: {
  sourceFileName: string;
  sourceContent: string;
  availableFiles?: RobotFile[];
  allFileContents?: Record<string, string>;
}): RobotState | null {
  const effectiveName = sourceFileName || 'robot.urdf.xacro';
  return parseEditableRobotSource({
    file: { name: effectiveName, format: 'xacro' },
    content: sourceContent,
    availableFiles,
    allFileContents: {
      ...allFileContents,
      [effectiveName]: sourceContent,
    },
  });
}

function collectChangedEntities<T extends { id: string; name: string }>(
  kind: EntityKind,
  beforeRecords: Record<string, T>,
  afterRecords: Record<string, T>,
): ChangedEntity[] {
  const changes: ChangedEntity[] = [];
  const visitedAfterIds = new Set<string>();

  Object.entries(beforeRecords).forEach(([key, beforeRecord]) => {
    const afterRecord = findByStableIdentity(afterRecords, key, beforeRecord.id);
    if (!afterRecord) {
      changes.push({ kind, beforeName: beforeRecord.name });
      return;
    }
    visitedAfterIds.add(afterRecord.id);
    if (!hasSameValue(beforeRecord, afterRecord)) {
      changes.push({
        kind,
        beforeName: beforeRecord.name,
        afterName: afterRecord.name,
      });
    }
  });

  Object.entries(afterRecords).forEach(([key, afterRecord]) => {
    if (
      !visitedAfterIds.has(afterRecord.id) &&
      !findByStableIdentity(beforeRecords, key, afterRecord.id)
    ) {
      changes.push({ kind, afterName: afterRecord.name });
    }
  });

  return changes;
}

function collectAllChangedEntities(
  beforeRobot: RobotData,
  afterRobot: RobotData,
): ChangedEntity[] {
  return [
    ...collectChangedEntities('link', beforeRobot.links, afterRobot.links),
    ...collectChangedEntities('joint', beforeRobot.joints, afterRobot.joints),
  ];
}

function findDirectEntity(
  sourceContent: string,
  kind: EntityKind,
  name: string,
) {
  return collectDirectChildren(sourceContent, 'robot').find(
    (element) =>
      element.tagName === kind && getElementAttribute(sourceContent, element, 'name') === name,
  ) ?? null;
}

function assertChangedEntitiesAreDirect(
  sourceContent: string,
  generatedContent: string,
  changes: ChangedEntity[],
): ReconcileXacroEditableSourceResult | null {
  for (const change of changes) {
    if (change.beforeName) {
      const sourceEntity = findDirectEntity(sourceContent, change.kind, change.beforeName);
      if (!sourceEntity) {
        return unsafe(
          `Cannot safely patch ${change.kind} "${change.beforeName}" because it is generated by Xacro.`,
        );
      }
      const sourceFragment = sourceContent.slice(sourceEntity.startOffset, sourceEntity.endOffset);
      if (XACRO_DYNAMIC_NODE_RE.test(sourceFragment)) {
        return unsafe(
          `Cannot safely patch ${change.kind} "${change.beforeName}" because it contains Xacro expressions.`,
        );
      }
    }
    if (change.afterName && !findDirectEntity(generatedContent, change.kind, change.afterName)) {
      return unsafe(
        `Cannot safely patch ${change.kind} "${change.afterName}" because generated output is ambiguous.`,
      );
    }
  }
  return null;
}

function unsafe(reason: string): ReconcileXacroEditableSourceResult {
  return { status: 'unsafe', reason };
}

function buildGeneratedAfter(afterRobot: RobotData): string {
  return ensureXacroNamespace(generateEditableRobotSource({
    format: 'xacro',
    robotState: asRobotState(afterRobot),
    includeHardware: 'auto',
    preserveMeshPaths: true,
  }));
}

export function reconcileXacroEditableSource({
  sourceContent,
  beforeRobot,
  afterRobot,
  sourceFileName,
  availableFiles = [],
  allFileContents = {},
}: ReconcileXacroEditableSourceOptions): ReconcileXacroEditableSourceResult {
  try {
    const parsedSource = parseXacro({
      sourceFileName,
      sourceContent,
      availableFiles,
      allFileContents,
    });
    if (!parsedSource) {
      return unsafe('The editable source is not valid Xacro.');
    }
    if (
      sourceSemanticHashForWorkspace(parsedSource, beforeRobot) !==
      sourceSemanticHash(beforeRobot)
    ) {
      return unsafe('The editable source no longer matches the robot before this mutation.');
    }

    const generatedAfter = buildGeneratedAfter(afterRobot);
    const unsafeChangedEntity = assertChangedEntitiesAreDirect(
      sourceContent,
      generatedAfter,
      collectAllChangedEntities(beforeRobot, afterRobot),
    );
    if (unsafeChangedEntity) return unsafeChangedEntity;

    const parsedGeneratedAfter = parseXacro({
      sourceFileName,
      sourceContent: generatedAfter,
      availableFiles,
      allFileContents,
    });
    if (!parsedGeneratedAfter) {
      return unsafe('The generated Xacro could not be parsed.');
    }
    if (sourceSemanticHash(parsedGeneratedAfter) !== sourceSemanticHash(afterRobot)) {
      return unsafe('The robot mutation cannot be represented losslessly as Xacro.');
    }

    const referencePatched = reconcileStandardUrdfReferences(
      sourceContent,
      beforeRobot,
      afterRobot,
    );
    const finePatched = applyFineGrainedUrdfPatches(
      referencePatched,
      generatedAfter,
      beforeRobot,
      afterRobot,
    );
    const sourceFile = sourceFileName || 'robot.urdf.xacro';
    const reconciled = resolveSourcePreservingExportContent({
      format: 'xacro',
      currentRobot: asRobotState(afterRobot),
      sourceFile: {
        name: sourceFile,
        format: 'xacro',
        content: finePatched,
      },
      availableFiles,
      allFileContents: {
        ...allFileContents,
        [sourceFile]: finePatched,
      },
      generatedContent: generatedAfter,
      xacroSourceModelMode: 'direct-changes',
    });
    if (reconciled.strategy !== 'source-preserved') {
      return unsafe('Xacro reconciliation would require replacing the complete source.');
    }

    const parsedReconciled = parseXacro({
      sourceFileName: sourceFile,
      sourceContent: reconciled.content,
      availableFiles,
      allFileContents,
    });
    if (
      !parsedReconciled ||
      sourceSemanticHash(parsedReconciled) !== sourceSemanticHash(afterRobot)
    ) {
      return unsafe('The patched Xacro did not preserve the requested robot semantics.');
    }

    return { status: 'patched', content: reconciled.content };
  } catch (error) {
    return unsafe(error instanceof Error ? error.message : 'Xacro reconciliation failed.');
  }
}
